name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "*/5 * * * *" 

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          #REPOSITORY: <gh_username/gh_username>
   
   
   
   
   
   
   
   
   
   
   
   
   
   
          
# jobs:
#   update-readme-with-wakatime:
#     runs-on: ubuntu-latest
#     steps: 
#       - name: Check out repository code
#         uses: actions/checkout@v2

#       - name: Update WakaTime stats
#         uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           SHOW_TITLE: true
#           BLOCKS: |
#             TIME_RANGE: all_time
#             SHOW_TIME: true
#             SHOW_MASKED_TIME: true
#             LANG_COUNT: 10
#             SHOW_COMMIT: False
#             SHOW_DAYS_OF_WEEK: False
#             SHOW_LANGUAGE: False
#             SHOW_EDITORS: False
#             SHOW_LANGUAGE_PER_REPO: False

          
